% Create a lpda antenna
% Generated by MATLAB(R) 23.2 and Antenna Toolbox 23.2.
% Generated on: 06-Jul-2025 14:40:07

%% Antenna Properties 

antennaObject = lpda;
antennaObject.BoardLength = 0.195;
antennaObject.BoardWidth = 0.65;
antennaObject.ArmLength = [0.3, 0.255, 0.2168, 0.1842, 0.1566, 0.1331, 0.1131, 0.0962, 0.0817, 0.0695, 0.0591, 0.0502, 0.0427, 0.0363];
antennaObject.ArmWidth = [0.0005, 0.00054, 0.00057, 0.00061, 0.00064, 0.00068, 0.00071, 0.00075, 0.00079, 0.00082, 0.00086, 0.00089, 0.00093, 0.001];
antennaObject.ArmSpacing = [0.03, 0.0255, 0.0217, 0.0184, 0.0157, 0.0133, 0.0113, 0.0096, 0.0082, 0.007, 0.0059, 0.005, 0.0043];
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 300*1e6;
% Define frequency range 
freqRange = (100:55:500)*1e6;
% Reference Impedance 
refImpedance = 50;
% sparameter
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)

