% Create a lpda antenna
% Generated by MATLAB(R) 23.2 and Antenna Toolbox 23.2.
% Generated on: 29-Jun-2025 15:24:32

%% Antenna Properties 

antennaObject = lpda;
antennaObject.BoardLength = 0.33658;
antennaObject.BoardWidth = 0.42244;
antennaObject.ArmLength = [0.174, 0.14616, 0.12277, 0.10313, 0.08663, 0.07277, 0.06113, 0.05135, 0.04313, 0.03623, 0.03043, 0.02556, 0.02147, 0.01804];
antennaObject.ArmWidth = [0.00032, 0.00031999, 0.00032003, 0.00031998, 0.00031998, 0.00032005, 0.00031997, 0.00031996, 0.00031996, 0.0003199, 0.00032008, 0.00032003, 0.00031998, 0.00038082];
antennaObject.ArmSpacing = [0.05568, 0.04677, 0.03929, 0.033, 0.02772, 0.02329, 0.01956, 0.01643, 0.0138, 0.01159, 0.00974, 0.00818, 0.00687];
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 300*1e6;
% Define frequency range 
freqRange = (100:55:500)*1e6;
% Reference Impedance 
refImpedance = 50;
% impedance
figure;
impedance(antennaObject, freqRange)
% sparameter
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)
% pattern
figure;
pattern(antennaObject, plotFrequency)
% azimuth
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)
% elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)

