% Create a lpda antenna
% Generated by MATLAB(R) 23.2 and Antenna Toolbox 23.2.
% Generated on: 06-Jul-2025 16:38:19

%% Antenna Properties 

antennaObject = lpda;
antennaObject.BoardLength = 0.3;
antennaObject.BoardWidth = 3;
antennaObject.ArmLength = [1.42, 1.207, 1.026, 0.8721, 0.7413, 0.6301, 0.5356, 0.4552, 0.3869, 0.3289, 0.2796, 0.2376];
antennaObject.ArmWidth = [0.142, 0.1207, 0.1026, 0.0872, 0.0741, 0.063, 0.0536, 0.0455, 0.0387, 0.0329, 0.0279];
antennaObject.ArmSpacing = [0.0028, 0.0024, 0.0021, 0.0017, 0.0015, 0.0013, 0.0011, 0.0009, 0.0008, 0.0007, 0.0006];
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 300*1e6;
% Define frequency range 
freqRange = (100:55:500)*1e6;
% Reference Impedance 
refImpedance = 50;
% pattern
figure;
pattern(antennaObject, plotFrequency)
% azimuth
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)
% elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)

