% Create a lpda antenna
% Generated by MATLAB(R) 23.2 and Antenna Toolbox 23.2.
% Generated on: 06-Jul-2025 17:16:00

%% Antenna Properties 

antennaObject = lpda;
antennaObject.BoardLength = 0.025;
antennaObject.BoardWidth = 0.031;
antennaObject.ArmLength = [0.0142, 0.01207, 0.01026, 0.008721, 0.007413, 0.006301, 0.005356, 0.004552, 0.003869, 0.003289, 0.002796, 0.002376];
antennaObject.ArmWidth = [0.00142, 0.001207, 0.001026, 0.000872, 0.000741, 0.00063, 0.000536, 0.000455, 0.000387, 0.000329, 0.000279];
antennaObject.ArmSpacing = [0.0028, 0.0024, 0.0021, 0.0017, 0.0015, 0.0013, 0.0011, 0.0009, 0.0008, 0.0007, 0.0006];
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 300*1e6;
% Define frequency range 
freqRange = (100:55:500)*1e6;
% Reference Impedance 
refImpedance = 50;
% pattern
figure;
pattern(antennaObject, plotFrequency)
% azimuth
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)
% elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)

